import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { BALANCE } from '../data/constants';
import { achievements, carTemplates, customerMessages, faults, randomEvents, upgrades } from '../data/gameData';
import type { CarJob } from '../types';

const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const genJob=(day:number):CarJob=>{const f=[pick(faults), day>8?pick(faults):undefined].filter(Boolean) as any[]; return {id:crypto.randomUUID(),carName:pick(carTemplates),condition:40+Math.floor(Math.random()*60),mileage:40000+Math.floor(Math.random()*220000),personality:pick(['cheery','grumpy','passive-aggressive','overconfident','terrified']),symptoms:Array.from(new Set(f.flatMap(x=>x.symptoms))).slice(0,4),faults:f,budget:300+day*55+Math.floor(Math.random()*300),deadline:70-Math.min(day,20),patience:90-Math.min(day*2,45),bonus:50+day*15,message:pick(customerMessages),hints:[]};};

type S={mode:'menu'|'career'|'endless'|'daily'|'upgrades'|'gameover';day:number;money:number;rep:number;stress:number;tool:number;parts:number;angry:number;time:number;queue:CarJob[];current?:CarJob;log:string[];done:number;events:string[];unlocked:string[];calledAssar:boolean;calledAtlas:boolean;start:(m:S['mode'])=>void;diag:(a:string)=>void;repair:(a:string)=>void;release:()=>void;nextDay:()=>void;buy:(id:string)=>void;reset:()=>void;callAssar:()=>void;callAtlas:()=>void;};

export const useGame=create<S>()(persist((set)=>({mode:'menu',day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:[],current:undefined,log:[],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false,
start:(mode)=>set(()=>{const q=[genJob(1),genJob(1),genJob(1)];return{mode,day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:q.slice(1),current:q[0],log:['Garage opened. Try not to cry.'],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false};}),
diag:(a)=>set((s)=>{if(!s.current) return s; const good=s.current.faults.some(f=>f.goodDiagnostics.includes(a)); const dt= good?18:26; const clue=good?`Clue: ${pick(s.current.faults).name}`:'Inconclusive. Mostly swearing.'; return {...s,time:Math.max(0,s.time-dt),money:s.money-(good?8:15),stress:Math.min(100,s.stress+(good?2:4)),log:[`${a}: ${clue}`,...s.log].slice(0,12)};}),
repair:(a)=>set((s)=>{if(!s.current) return s; const goodCount=s.current.faults.filter(f=>f.goodRepairs.includes(a)).length; const bad=a==='Dodgy fix'?0:goodCount===0?1:0; let rep=s.rep,stress=s.stress,money=s.money,time=s.time,tool=s.tool,parts=s.parts; if(goodCount){money-=40;parts=Math.max(0,parts-1);stress=Math.max(0,stress-2);rep+=1;} else if(a==='Do nothing and hope'){stress+=6;rep-=2;} else {money-=30;stress+=5;rep-=2;} if(a==='Dodgy fix'){money-=10;stress+=1;} time-=24; tool-=2+bad; return {...s,rep,stress:Math.min(100,stress),money,tool,time:Math.max(0,time),parts,log:[`${a}: ${goodCount?`fixed ${goodCount} issue(s)`:'might have made it worse'}`,...s.log].slice(0,12)};}),
release:()=>set((s)=>{if(!s.current)return s; const fixed=s.current.faults.filter(f=>s.log.some(l=>f.goodRepairs.some(r=>l.startsWith(r)))).length; const ratio=fixed/s.current.faults.length; const payout=Math.floor(s.current.budget*(0.3+ratio))+ (ratio===1? s.current.bonus:0); const angry= ratio<0.4?1:0; const repDelta= ratio===1?4:ratio>0.5?1:-3; const stress= Math.min(100,Math.max(0,s.stress+(ratio===1?-5:6)+angry*3)); const next=s.queue[0]; const q=[...s.queue.slice(1),genJob(s.day)]; const mode=(s.money+payout<0||s.rep+repDelta<=BALANCE.failRep||s.angry+angry>=BALANCE.maxAngry||stress>=100)?'gameover':s.mode; return {...s,money:s.money+payout,rep:s.rep+repDelta,stress,angry:s.angry+angry,current:next,queue:q,done:s.done+1,calledAtlas:false,log:[`Job released: £${payout}, rep ${repDelta>0?'+':''}${repDelta}`,...s.log].slice(0,12),mode};}),
nextDay:()=>set((s)=>{const day=s.day+1; const ev=pick(randomEvents); if(day>BALANCE.maxDays&&s.mode==='career') return {...s,mode:'gameover',log:['You survived 30 days. Absolute hero.',...s.log]}; return {...s,day,time:BALANCE.dayMinutes,tool:Math.min(100,s.tool+10),parts:s.parts+2,stress:Math.max(0,s.stress-12),events:[ev,...s.events].slice(0,6),calledAssar:false,log:[`Day ${day}: ${ev}`,...s.log].slice(0,12)};}),
buy:(id)=>set((s)=>{const u=upgrades.find(x=>x.id===id); if(!u||s.money<u.cost||s.unlocked.includes(id)) return s; return {...s,money:s.money-u.cost,unlocked:[...s.unlocked,id],stress:Math.max(0,s.stress-(u.effect===0?5:0)),rep:s.rep+(u.effect===2?2:0),log:[`Purchased ${u.name}`,...s.log]};}),
callAssar:()=>set((s)=>s.calledAssar?s:{...s,calledAssar:true,rep:s.rep+1,log:['Assar: "Start with spark, fuel, air, not vibes."',...s.log]}),
callAtlas:()=>set((s)=>{if(!s.current||s.calledAtlas)return s; return {...s,calledAtlas:true,log:[`Atlas hint: check ${pick(s.current.faults).goodDiagnostics[0]}.`,...s.log]};}),
reset:()=>set(()=>({mode:'menu',day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:[],current:undefined,log:[],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false}))}),{name:'garage-chaos-save'}));

export { upgrades, achievements };
