import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { BALANCE } from '../data/constants';
import { achievements, carTemplates, customerMessages, faults, randomEvents, upgrades } from '../data/gameData';
import type { CarJob } from '../types';

const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const genJob=(day:number):CarJob=>{const f=[pick(faults), day>8?pick(faults):undefined].filter(Boolean) as any[]; return {id:crypto.randomUUID(),carName:pick(carTemplates),condition:40+Math.floor(Math.random()*60),mileage:40000+Math.floor(Math.random()*220000),personality:pick(['cheery','grumpy','passive-aggressive','overconfident','terrified']),symptoms:Array.from(new Set(f.flatMap(x=>x.symptoms))).slice(0,4),faults:f,budget:300+day*55+Math.floor(Math.random()*300),deadline:70-Math.min(day,20),patience:90-Math.min(day*2,45),bonus:50+day*15,message:pick(customerMessages),hints:[]};};

type Inv={battery:number;electrical:number;brake:number;engine:number};
type S={mode:'menu'|'career'|'endless'|'daily'|'upgrades'|'gameover';day:number;money:number;rep:number;stress:number;tool:number;parts:number;angry:number;time:number;queue:CarJob[];current?:CarJob;log:string[];done:number;events:string[];unlocked:string[];calledAssar:boolean;calledAtlas:boolean;combo:number;trust:number;inventory:Inv;start:(m:S['mode'])=>void;diag:(a:string)=>void;repair:(a:string)=>void;release:()=>void;nextDay:()=>void;buy:(id:string)=>void;reset:()=>void;callAssar:()=>void;callAtlas:()=>void;buyPart:(kind:keyof Inv)=>void;};

const repairPartMap:Record<string,keyof Inv>={'Replace battery':'battery','Replace alternator':'electrical','Fix ground wire':'electrical','Replace starter':'electrical','Replace fuel pump':'engine','Replace ignition coil':'engine','Replace brake pads':'brake','Replace wheel cylinder':'brake','Patch exhaust leak':'engine','Replace lambda sensor':'engine','Replace timing belt':'engine','Replace crank sensor':'engine'};
const partCosts:Record<keyof Inv,number>={battery:80,electrical:55,brake:65,engine:95};

export const useGame=create<S>()(persist((set)=>({mode:'menu',day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:[],current:undefined,log:[],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false,combo:0,trust:55,inventory:{battery:1,electrical:1,brake:1,engine:1},
start:(mode)=>set(()=>{const q=[genJob(1),genJob(1),genJob(1)];return{mode,day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:q.slice(1),current:q[0],log:['Garage opened. Try not to cry.'],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false,combo:0,trust:55,inventory:{battery:1,electrical:1,brake:1,engine:1}};}),
diag:(a)=>set((s)=>{if(!s.current) return s; const hinted=s.current.hints.join('|'); const newHint = s.current.faults.find(f=>f.goodDiagnostics.includes(a) && !hinted.includes(f.name)); const good=Boolean(newHint); const dt= good?14:24; const nextHints = newHint ? [...s.current.hints, `Likely: ${newHint.name}`] : s.current.hints; return {...s,current:{...s.current,hints:nextHints,patience:Math.max(0,s.current.patience-(good?6:10))},time:Math.max(0,s.time-dt),money:s.money-(good?6:14),stress:Math.min(100,s.stress+(good?1:4)),log:[`${a}: ${good?`new clue (${newHint?.name})`:'inconclusive noise and vibes'}`,...s.log].slice(0,14)};}),
repair:(a)=>set((s)=>{if(!s.current) return s; const needed=repairPartMap[a]; if(needed && s.inventory[needed]<=0) return {...s,log:[`Need ${needed} stock before ${a}.`,...s.log].slice(0,14),stress:Math.min(100,s.stress+2)}; const goodCount=s.current.faults.filter(f=>f.goodRepairs.includes(a)).length; const bad=a==='Dodgy fix'?0:goodCount===0?1:0; let rep=s.rep,stress=s.stress,money=s.money,time=s.time,tool=s.tool,parts=s.parts,trust=s.trust; const inventory={...s.inventory}; if(needed) inventory[needed]-=1; if(goodCount){money-=35;parts=Math.max(0,parts-1);stress=Math.max(0,stress-3);rep+=1;trust=Math.min(100,trust+1);} else if(a==='Do nothing and hope'){stress+=8;rep-=3;trust-=3;} else {money-=30;stress+=5;rep-=2;trust-=2;} if(a==='Dodgy fix'){money-=10;stress+=2;trust-=4;} time-=22; tool-=2+bad; return {...s,inventory,rep,trust:Math.max(0,trust),stress:Math.min(100,stress),money,tool,time:Math.max(0,time),parts,current:{...s.current,patience:Math.max(0,s.current.patience-(goodCount?8:14))},log:[`${a}: ${goodCount?`fixed ${goodCount} issue(s)`:'possibly made a new problem'}`,...s.log].slice(0,14)};}),
release:()=>set((s)=>{if(!s.current)return s; const fixed=s.current.faults.filter(f=>s.log.some(l=>f.goodRepairs.some(r=>l.startsWith(r)))).length; const ratio=fixed/s.current.faults.length; const clueBonus=Math.min(0.25,s.current.hints.length*0.06); const paceBonus=s.current.patience>35?0.15:0; const comboBonus=Math.min(0.3,s.combo*0.05); const payout=Math.floor(s.current.budget*(0.3+ratio+clueBonus+paceBonus+comboBonus))+ (ratio===1? s.current.bonus:0); const angry= ratio<0.4||s.current.patience<15?1:0; const repDelta= ratio===1?4:ratio>0.5?1:-3; const newCombo = ratio===1 ? s.combo+1 : 0; const stress= Math.min(100,Math.max(0,s.stress+(ratio===1?-6:7)+angry*3)); const next=s.queue[0]; const q=[...s.queue.slice(1),genJob(s.day)]; const mode=(s.money+payout<0||s.rep+repDelta<=BALANCE.failRep||s.angry+angry>=BALANCE.maxAngry||stress>=100)?'gameover':s.mode; return {...s,money:s.money+payout,rep:s.rep+repDelta,stress,combo:newCombo,trust:Math.min(100,Math.max(0,s.trust+(ratio===1?2:-2))),angry:s.angry+angry,current:next,queue:q,done:s.done+1,calledAtlas:false,log:[`Job released: £${payout}, rep ${repDelta>0?'+':''}${repDelta}, combo x${newCombo}`,...s.log].slice(0,14),mode};}),
nextDay:()=>set((s)=>{const day=s.day+1; const ev=pick(randomEvents); if(day>BALANCE.maxDays&&s.mode==='career') return {...s,mode:'gameover',log:['You survived 30 days. Absolute hero.',...s.log]}; const partsBoost=ev.includes('Parts van late')?0:1; const stressDelta=ev.includes('biscuit')?-18:-10; return {...s,day,time:BALANCE.dayMinutes,tool:Math.min(100,s.tool+10),inventory:{battery:s.inventory.battery+partsBoost,electrical:s.inventory.electrical+partsBoost,brake:s.inventory.brake+partsBoost,engine:s.inventory.engine+partsBoost},parts:s.parts+partsBoost,stress:Math.max(0,s.stress+stressDelta),events:[ev,...s.events].slice(0,6),calledAssar:false,log:[`Day ${day}: ${ev} (${partsBoost?'+stock':'no delivery'})`,...s.log].slice(0,14)};}),
buyPart:(kind)=>set((s)=>s.money<partCosts[kind]?{...s,log:[`Not enough cash for ${kind} part.`,...s.log].slice(0,14)}:{...s,money:s.money-partCosts[kind],inventory:{...s.inventory,[kind]:s.inventory[kind]+1},log:[`Bought ${kind} part for £${partCosts[kind]}.`,...s.log].slice(0,14)}),
buy:(id)=>set((s)=>{const u=upgrades.find(x=>x.id===id); if(!u||s.money<u.cost||s.unlocked.includes(id)) return s; return {...s,money:s.money-u.cost,unlocked:[...s.unlocked,id],stress:Math.max(0,s.stress-(u.effect===0?5:0)),rep:s.rep+(u.effect===2?2:0),log:[`Purchased ${u.name}`,...s.log]};}),
callAssar:()=>set((s)=>s.calledAssar?s:{...s,calledAssar:true,rep:s.rep+1,log:['Assar: "Start with spark, fuel, air, then stop guessing."',...s.log]}),
callAtlas:()=>set((s)=>{if(!s.current||s.calledAtlas)return s; return {...s,calledAtlas:true,current:{...s.current,hints:[...s.current.hints,`Atlas says: ${pick(s.current.faults).goodDiagnostics[0]}`]},log:[`Atlas hint added to work order.`,...s.log]};}),
reset:()=>set(()=>({mode:'menu',day:1,money:BALANCE.startMoney,rep:BALANCE.startRep,stress:BALANCE.startStress,tool:100,parts:6,angry:0,time:BALANCE.dayMinutes,queue:[],current:undefined,log:[],done:0,events:[],unlocked:[],calledAssar:false,calledAtlas:false,combo:0,trust:55,inventory:{battery:1,electrical:1,brake:1,engine:1}}))}),{name:'garage-chaos-save'}));

export { upgrades, achievements };
