import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { achievements, carTemplates, customerMessages, diagnostics, faults, randomEvents, repairs, upgrades } from '../data/gameData';
import type { CarJob, DiagnosticAction, RepairAction } from '../types';
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const mk=(day:number):CarJob=>{const fs=[pick(faults), day>8?pick(faults):undefined].filter(Boolean) as any[];return {id:crypto.randomUUID(),carName:pick(carTemplates),condition:35+Math.random()*65|0,mileage:20000+Math.random()*250000|0,personality:pick(['chatty','impatient','doomposting','quiet menace']),symptoms:[...new Set(fs.flatMap((f:any)=>f.symptoms))].slice(0,4),faults:fs,budget:260+day*58+(Math.random()*240|0),deadline:80-Math.min(day*2,45),patience:90-Math.min(day,35),bonus:40+day*14,message:pick(customerMessages),hints:[],resolved:[]};};
type S={mode:'menu'|'career'|'endless'|'daily'|'gameover'|'pause'|'upgrades';day:number;money:number;rep:number;stress:number;time:number;tool:number;queue:CarJob[];current?:CarJob;log:string[];done:number;angry:number;unlocked:string[];start:(m:'career'|'endless'|'daily')=>void;diag:(d:DiagnosticAction)=>void;repair:(r:RepairAction)=>void;release:()=>void;nextDay:()=>void;buy:(id:string)=>void;reset:()=>void;togglePause:()=>void;};
export const useGame=create<S>()(persist((set)=>({mode:'menu',day:1,money:800,rep:55,stress:8,time:480,tool:100,queue:[],log:[],done:0,angry:0,unlocked:[],
start:(mode)=>set(()=>{const q=[mk(1),mk(1),mk(1)];return{mode,day:1,money:800,rep:55,stress:8,time:480,tool:100,queue:q.slice(1),current:q[0],log:['Shutters up. Keep it together.'],done:0,angry:0,unlocked:[]};}),
diag:(d)=>set(s=>{if(!s.current||s.mode==='pause')return s;const hit=s.current.faults.find(f=>f.goodDiagnostics.includes(d)&&!s.current?.hints.includes(f.name));const hints=hit?[...s.current.hints,hit.name]:s.current.hints;return {...s,current:{...s.current,hints,patience:Math.max(0,s.current.patience-(hit?5:9))},time:Math.max(0,s.time-(hit?12:20)),money:s.money-(hit?8:16),stress:Math.min(100,s.stress+(hit?1:4)),log:[`${d}: ${hit?'solid clue found':'noisy dead end'}`,...s.log].slice(0,12)};}),
repair:(r)=>set(s=>{if(!s.current||s.mode==='pause')return s;const fixed=s.current.faults.filter(f=>f.goodRepairs.includes(r)&&!s.current?.resolved.includes(f.id));const worsened=s.current.faults.filter(f=>f.wrongRepairs.includes(r));const resolved=[...s.current.resolved,...fixed.map(f=>f.id)];const delta=fixed.length-worsened.length;return {...s,current:{...s.current,resolved,patience:Math.max(0,s.current.patience-(delta>0?7:12)),condition:Math.max(0,Math.min(100,s.current.condition+delta*6))},money:s.money-(r==='Dodgy fix'?10:30),time:Math.max(0,s.time-24),rep:s.rep+(delta>0?1:-2),stress:Math.min(100,Math.max(0,s.stress+(delta>0?-3:6))),log:[`${r}: ${delta>0?`progress (${fixed.length})`:'made it worse'}`,...s.log].slice(0,12)};}),
release:()=>set(s=>{if(!s.current)return s;const fixed=s.current.resolved.length,all=s.current.faults.length;const ratio=fixed/all;const payout=Math.floor(s.current.budget*(0.4+ratio)+(ratio===1?s.current.bonus:0));const repDelta=ratio===1?4:ratio>0.6?1:-4;const angry=ratio<0.4?1:0;const next=s.queue[0],q=[...s.queue.slice(1),mk(s.day)];const stress=Math.min(100,Math.max(0,s.stress+(ratio===1?-6:8)));const mode=(s.money+payout<0||s.rep+repDelta<5||stress>=100||s.angry+angry>11)?'gameover':s.mode;return {...s,money:s.money+payout,rep:s.rep+repDelta,stress,angry:s.angry+angry,done:s.done+1,current:next,queue:q,mode,log:[`Released: payout £${payout}, rep ${repDelta}`,...s.log].slice(0,12)};}),
nextDay:()=>set(s=>{const day=s.day+1;if(day>30&&s.mode==='career')return {...s,mode:'gameover',log:['Career complete. Thirty days survived.',...s.log]};const ev=pick(randomEvents);return {...s,day,time:480,tool:Math.min(100,s.tool+8),stress:Math.max(0,s.stress-8),money:s.money+20,log:[`Day ${day}: ${ev}`,...s.log].slice(0,12)};}),
buy:(id)=>set(s=>{const u=upgrades.find(x=>x.id===id);if(!u||s.money<u.cost||s.unlocked.includes(id))return s;return {...s,money:s.money-u.cost,unlocked:[...s.unlocked,id],stress:Math.max(0,s.stress-(u.effect==='stress'?u.amount*2:0)),rep:s.rep+(u.effect==='rep'?u.amount:0)};}),
togglePause:()=>set(s=>({...s,mode:s.mode==='pause'?'career':'pause'})),
reset:()=>set(()=>({mode:'menu',day:1,money:800,rep:55,stress:8,time:480,tool:100,queue:[],log:[],done:0,angry:0,unlocked:[]}))
}),{name:'garage-chaos-save'}));
export { diagnostics, repairs, achievements, upgrades };
