import { motion } from 'framer-motion';
import { useEffect, useRef } from 'react';
import { achievements, diagnostics, repairs, upgrades, useGame } from './store/gameStore';
import { sfx } from './utils/audio';

const palette={bg:'#101218',panel:'#1a2030',line:'#3a4b68',ok:'#4ea96e',bad:'#b34d4d',car:'#5c81c9',smoke:'#778899',gold:'#d8b24c'};
const carSprite=[[0,1,1,1,0],[1,1,1,1,1],[1,0,1,0,1],[1,1,1,1,1]];
const Btn=({t,on}:{t:string;on:()=>void})=><button aria-label={t} onClick={()=>{sfx.click.play();on();}} className='px-2 py-1 text-xs rounded border border-slate-500 bg-slate-900 hover:bg-slate-800'>{t}</button>;

function GarageCanvas(){const c=useRef<HTMLCanvasElement>(null);const g=useGame();useEffect(()=>{const cv=c.current;if(!cv)return;const x=cv.getContext('2d')!;x.imageSmoothingEnabled=false;let f=0;const loop=()=>{f++;x.fillStyle=palette.bg;x.fillRect(0,0,320,180);x.fillStyle=palette.panel;x.fillRect(8,12,304,156);x.strokeStyle=palette.line;x.strokeRect(8,12,304,156);for(let gy=0;gy<9;gy++)for(let gx=0;gx<16;gx++){x.fillStyle=(gx+gy)%2? '#212a3d':'#1d2535';x.fillRect(12+gx*18,20+gy*16,16,14);}if(g.current){const cx=125,cy=76;for(let yy=0;yy<carSprite.length;yy++)for(let xx=0;xx<carSprite[yy].length;xx++)if(carSprite[yy][xx]){x.fillStyle=palette.car;x.fillRect(cx+xx*12,cy+yy*12,12,12);}if(g.current.condition<50){x.fillStyle=palette.bad;x.fillRect(cx+12,cy+8,12,6);}if(f%40<20){x.fillStyle=palette.smoke;x.fillRect(cx+40,cy-8,6,6);x.fillRect(cx+46,cy-12,4,4);}}x.fillStyle=palette.gold;x.fillRect(16,16,6,6);x.fillStyle='#fff';x.font='8px monospace';x.fillText(`DAY ${g.day}  CASH ${g.money}  REP ${g.rep}  STRESS ${g.stress}`,28,22);requestAnimationFrame(loop);};loop();},[g.day,g.money,g.rep,g.stress,g.current]);return <canvas aria-label='garage-canvas' width={320} height={180} className='w-full max-w-3xl border border-slate-700 [image-rendering:pixelated]'/>;}

export default function App(){const g=useGame();useEffect(()=>{sfx.ambient.play();return ()=>{sfx.ambient.stop();};},[]);
if(g.mode==='menu')return <main className='p-6 min-h-screen bg-slate-950 text-slate-100'><h1 className='text-3xl font-black'>Garage Chaos Simulator</h1><p className='text-sm mt-2'>Repair cursed cars, protect your reputation, and survive thirty days.</p><div className='flex gap-2 mt-4'><Btn t='Career' on={()=>g.start('career')}/><Btn t='Endless chaos' on={()=>g.start('endless')}/><Btn t='Daily challenge' on={()=>g.start('daily')}/></div></main>;
return <main className='min-h-screen bg-slate-950 text-slate-100 p-3 md:p-5'>
<div className='grid lg:grid-cols-3 gap-3'><motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className='lg:col-span-2 bg-slate-900/70 p-3 rounded border border-slate-700'><GarageCanvas /></motion.section>
<section className='bg-slate-900/70 p-3 rounded border border-slate-700 text-sm'><h2 className='font-bold mb-2'>Current job</h2>{g.current&&<><div>{g.current.carName} • {g.current.mileage} mi</div><div>Condition {g.current.condition} • Patience {g.current.patience}</div><div className='text-xs mt-1'>{g.current.message}</div><div className='mt-1 text-xs'>Symptoms: {g.current.symptoms.join(', ')}</div><div className='text-xs'>Clues: {g.current.hints.join(' | ')||'none'}</div></>}<div className='mt-2 flex flex-wrap gap-1'><Btn t='Release car' on={()=>{g.release();sfx.cash.play();}}/><Btn t='Next day' on={g.nextDay}/><Btn t='Pause' on={g.togglePause}/><Btn t='Reset save' on={g.reset}/></div></section>
<section className='bg-slate-900/70 p-3 rounded border border-slate-700'><h3 className='font-semibold text-sm'>Diagnostics</h3><div className='flex flex-wrap gap-1 mt-2'>{diagnostics.map(d=><Btn key={d} t={d} on={()=>g.diag(d)} />)}</div></section>
<section className='bg-slate-900/70 p-3 rounded border border-slate-700'><h3 className='font-semibold text-sm'>Repairs</h3><div className='flex flex-wrap gap-1 mt-2'>{repairs.map(r=><Btn key={r} t={r} on={()=>{g.repair(r);(r==='Dodgy fix'?sfx.fail:sfx.click).play();}} />)}</div></section>
<section className='bg-slate-900/70 p-3 rounded border border-slate-700'><h3 className='font-semibold text-sm'>Upgrades</h3><div className='max-h-36 overflow-auto text-xs'>{upgrades.map(u=><button key={u.id} onClick={()=>g.buy(u.id)} className='block w-full text-left py-1 border-b border-slate-700'>{u.name} £{u.cost}</button>)}</div></section>
<section className='bg-slate-900/70 p-3 rounded border border-slate-700 lg:col-span-3'><h3 className='font-semibold text-sm'>Job log / queue</h3><div className='grid md:grid-cols-2 gap-2 text-xs'><div>{g.log.map((l,i)=><div key={i}>{l}</div>)}</div><div>{g.queue.map(q=><div key={q.id}>{q.carName}</div>)}</div></div><div className='mt-2 text-xs'>Achievements: {achievements.filter((_,i)=>g.done>=i+1).join(', ')||'none'}</div></section>
</div>{g.mode==='gameover'&&<section className='mt-3 p-3 rounded bg-red-900/70'>Game over. Jobs completed: {g.done}</section>}</main>;}
